### ISSUE TITLE
FASTMAP(d=3) returns same value in columns 0 and 2.

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#10]
Using `new DR(data, ...P, 3)` with FASTMAP results in a planar diagram, with transformed[0] === transformed[2]

<img width="353" alt="Capture d’écran 2020-10-20 à 21 27 25" src="https://user-images.githubusercontent.com/7001/96634627-14dcee00-131b-11eb-8282-06634cfbc272.png">

https://observablehq.com/d/f0ac59b22d266632

(I added plotly to render the maps in 3D)

**Comment by saehm** [comment]
As it turns out, i wasn't paying attention to cases d > 2. At least, I found the bug in the code. I will fix it.

**Comment by saehm** [comment]
should be fixed now :)

![image](https://user-images.githubusercontent.com/37041252/96705686-e8b28300-1395-11eb-8264-2ace8b61fc9e.png)
