### ISSUE TITLE
Sammon Mapping?

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#14]
I was going to ask about Sammon Mapping and just saw this JS implementation https://observablehq.com/@jonnydedwards/animated-sammon-map

- WP https://en.wikipedia.org/wiki/Sammon_mapping
- python implementation: https://github.com/tompollard/sammon

**Comment by Fil** [comment]
I see SAMMON is implemented, but there is a bug when calling the generator version: max_iter is not defined (line 118).

**Comment by saehm** [comment]
I started implementing it but was not able to finish it. In the meanwhile, I added the implementation from https://observablehq.com/@jonnydedwards/animated-sammon-map for now.

Thanks :)
