### ISSUE TITLE
Link to Observable examples from README

### ISSUE THREAD

**Issue by curran** [saehm/DruidJS#15]
I notice in your [conference talk](https://youtu.be/bi6FfsWV_9k?t=2469), you present some examples in Observable.

It would be useful to link to them from the README here.

Great work!

**Comment by curran** [comment]
Surprisingly, I don't see any examples here https://observablehq.com/@saehm

**Comment by saehm** [comment]
Thanks, I added them :+1:

**Comment by saehm** [comment]
> Surprisingly, I don't see any examples here https://observablehq.com/@saehm

My examples are here: https://observablehq.com/@saehrimnir

**Comment by curran** [comment]
Nice!
