### ISSUE TITLE
Could not find a declaration file for module '@saehrimnir/druidjs' / module has no exports error

### ISSUE THREAD

**Issue by filipforgac** [saehm/DruidJS#28]
I am trying to incorporate your library into my project. I am using Yarn package manager and I installed the package with `yarn add @saehrimnir/druidjs`. The installation finished successfully and I can see the package in node_modules. However, upon importing it I get this message:
![image](https://user-images.githubusercontent.com/86187197/162993715-8df7c479-6c74-48c0-817e-cf36ecbdc700.png)

Moreover, after `yarn start` I get an error in the console like this, even though the modules from druid import are clearly recognized when I try to use them:
![image](https://user-images.githubusercontent.com/86187197/162994254-890731c9-ab04-4109-be68-e7a729b99b1d.png)
![image](https://user-images.githubusercontent.com/86187197/162994000-39c4be88-cc10-45f4-9252-abe0e6f0f82b.png)

**Comment by saehm** [comment]
Hey,

try `import * as druid from "@saehrimnir/druidjs/dist/druid.js`.

**Comment by filipforgac** [comment]
Hey. That resulted in the same error, but fortunately `import * as druid from "@saehrimnir/druidjs/dist/druid.esm"` worked. I don't know why are the other imports problematic, but this is a solution for now.
