### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#34]
Hello,

I've tried to upgrade my [older notebook](https://observablehq.com/@fil/druidjs-worker) from 0.3.5 to 0.7.1, and several of the methods break (FASTMAP, PCA, etc). I'm not sure where to find the new API documentation so I can fix this? Thanks!

**Comment by saehm** [comment]
Hey,

the documentation for FASTMAP is here: https://saehm.github.io/DruidJS/FASTMAP.html

I hope this helps!

**Comment by Fil** [comment]
I see. So we need one of:

>      yield druid[dr_method].transform(data, {});
>      yield* druid[dr_method].generator(data, {});

How can I distinguish the methods that have a working generator? (I think it's the same question as https://github.com/saehm/DruidJS/issues/13#issuecomment-718252666 :) )

**Comment by saehm** [comment]
I fixed the issue of the methods which need a neighbor parameter.
I already added the generator function for all DR methods when you were talking about this here: https://github.com/saehm/DruidJS/issues/13#issuecomment-718252666. 
But they did not work yet. With version 0.7.3, your notebook works for all DR techniques with your code, but also with this code:

```js
result = Generators.observe(
  worker(
    function dr({ dr_method, data }) {
      return druid[dr_method].generator(data); // show the steps
    },
    { dr_method, data },
    `
importScripts(${JSON.stringify(
      await require.resolve("@saehrimnir/druidjs@^0.7.3")
    )});
`
  )
)
```
