### ISSUE TITLE
LDA has fixed dimension d=2

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#4]
When I pass d=3 or d=4, all the dimred methods work except:
- LDA, which returns 2D vectors
- LSE, crashes with `A.concat(B, "vertical"): A and B need same number of columns, A has 4 columns, B has 2 columns.`

**Comment by saehm** [comment]
Hey, i think i have fixed this issue.

**Comment by Fil** [comment]
Yes, it works now. Thank you!
