### ISSUE TITLE
static properties are TC39

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#8]
`static parameter_list = [];` breaks on Safari

See https://github.com/tc39/proposal-static-class-features

We can either wait for Safari to catch up, or use normal properties instead.

**Comment by saehm** [comment]
This line doesn't do much. I will replace it with a getter and a setter, then it should work.

**Comment by saehm** [comment]
Sorry, now with 0.3.4, it should work. I tested it with the webkit browser epiphany, since i don't get Safari to run on Linux.

**Comment by Fil** [comment]
perfect !
