### ISSUE TITLE
Topomap?

### ISSUE THREAD

**Issue by Fil** [saehm/DruidJS#9]
*TopoMap: A 0-dimensional Homology Preserving Projection of High-Dimensional Data*
Harish Doraiswamy, Julien Tierny, Paulo J. S. Silva, Luis Gustavo Nonato, Claudio Silva

See https://arxiv.org/abs/2009.01512 [Submitted on 3 Sep 2020]

the current reference implementation in in C++ but the code is really short https://github.com/harishd10/TopoMap/blob/master/cpp/TopoMap.cpp

**Comment by saehm** [comment]
I was planning to add this one next :)

**Comment by Fil** [comment]
fantastic!

**Comment by chriswillis** [comment]
Great work, @saehm!

**Comment by saehm** [comment]
I think i got it to run!

https://observablehq.com/d/12c6dd7a83f9194c

**Comment by Fil** [comment]
Congratulations! And it's really fun to watch!!

(Note: I tried to check it on an iPhone first, but the module results in an error on Chrome and Firefox.)
